name: Deployment
run-name: ${{github.actor}} - ${{github.ref_name}}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
      version:
        required: true
        description: 'Docker image version to deploy (e.g., Git SHA)'
        type: string
      helm-release-name:
        description: 'Name of the Helm release'
        type: string
        default: 'todoapp'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  deploy:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Helm Package
        uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          config: cluster.yml

      - name: Set Up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Helm Dry Run
        run: |
          helm install ${{ inputs.helm-release-name }} ./*.tgz \
            --dry-run --debug \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName}} \
            --set image.tag=${{ inputs.version }}

      - name: Helm Upgrade
        run: |
          helm upgrade --install --atomic --wait --timeout 3600s --debug ${{ inputs.helm-release-name }} ./*.tgz \
          --set image.repository="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName}} \
          --set image.tag=${{ inputs.version}}